import { ActivityCategory } from './activity';
import { GoalStatus } from './goal';
import { RecurrenceFrequency, RecomputeMode } from './recurrence';

export const ErrorCodes = {
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  RBAC_ROLE_DENIED: 'RBAC_ROLE_DENIED',
  USER_EMAIL_DUPLICATE: 'USER_EMAIL_DUPLICATE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_PASSWORD_INVALID: 'USER_PASSWORD_INVALID',
  ACTIVITY_CATEGORY_INVALID: `ACTIVITY_CATEGORY_INVALID:${Object.values(ActivityCategory).join('|')}`,
  ACTIVITY_NOT_FOUND: 'ACTIVITY_NOT_FOUND',
  FACTOR_NOT_FOUND: 'FACTOR_NOT_FOUND',
  GOAL_STATUS_INVALID: `GOAL_STATUS_INVALID:${Object.values(GoalStatus).join('|')}`,
  GOAL_NOT_FOUND: 'GOAL_NOT_FOUND',
  TEMPLATE_FREQUENCY_INVALID: `TEMPLATE_FREQUENCY_INVALID:${Object.values(RecurrenceFrequency).join('|')}`,
  TEMPLATE_RECOMPUTE_MODE_INVALID: `TEMPLATE_RECOMPUTE_MODE_INVALID:${Object.values(RecomputeMode).join('|')}`,
  TEMPLATE_DATE_RANGE_INVALID: 'TEMPLATE_DATE_RANGE_INVALID',
  TEMPLATE_FACTOR_REQUIRED: 'TEMPLATE_FACTOR_REQUIRED',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
  TEMPLATE_NOT_ENABLED: 'TEMPLATE_NOT_ENABLED',
  TEMPLATE_ALREADY_PAUSED: 'TEMPLATE_ALREADY_PAUSED',
  TEMPLATE_BACKFILL_BUSY: 'TEMPLATE_BACKFILL_BUSY',
  AUDIT_LOG_FAILED: 'AUDIT_LOG_FAILED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  DATABASE_FAILED: 'DATABASE_FAILED'
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

