import { ActivityCategory } from './activity';
import { GoalStatus } from './goal';
import { RecurrenceFrequency } from './recurrence';

export const LogTemplates = {
  USER_REGISTER_START: 'User[email={email}] register start',
  USER_REGISTER_SUCCESS: 'User[id={id}] register success in region={region}',
  USER_REGISTER_FAILED: 'User[email={email}] register failed: {reason}',
  USER_LOGIN_START: 'User[email={email}] login start',
  USER_LOGIN_SUCCESS: 'User[id={id}] login success roles={roles}',
  USER_LOGIN_FAILED: 'User[email={email}] login failed: {reason}',
  USER_PROFILE_UPDATE_START: 'User[id={id}] profile update start field={field}',
  USER_PROFILE_UPDATE_SUCCESS: 'User[id={id}] profile update success region={region}',
  USER_PROFILE_UPDATE_FAILED: 'User[id={id}] profile update failed field={field}: {reason}',
  ACTIVITY_LIST_START: `Activity list start category values=${Object.values(ActivityCategory).join(',')}`,
  ACTIVITY_CREATE_START: 'Activity[user_id={userId}] create start category={category} sub_type={subType}',
  ACTIVITY_CREATE_SUCCESS: 'Activity[id={id}] create success carbon_value={carbonValue}',
  ACTIVITY_CREATE_FAILED: 'Activity[id={id}] create failed: {field} {reason}',
  ACTIVITY_UPDATE_START: 'Activity[id={id}] update start fields={fields}',
  ACTIVITY_UPDATE_SUCCESS: 'Activity[id={id}] update success carbon_value={carbonValue}',
  ACTIVITY_UPDATE_FAILED: 'Activity[id={id}] update failed: {field} {reason}',
  ACTIVITY_DELETE_SUCCESS: 'Activity[id={id}] delete success',
  GOAL_LIST_START: `Goal list start statuses=${Object.values(GoalStatus).join(',')}`,
  GOAL_CREATE_START: 'Goal[user_id={userId}] create start status={status}',
  GOAL_CREATE_SUCCESS: 'Goal[id={id}] create success target_value={targetValue}',
  GOAL_CREATE_FAILED: 'Goal[id={id}] create failed: {field} {reason}',
  GOAL_PROGRESS_CALCULATED: 'Goal[id={id}] progress calculated current={currentValue} target={targetValue}',
  TEMPLATE_LIST_START: `ActivityTemplate list start frequencies=${Object.values(RecurrenceFrequency).join(',')}`,
  TEMPLATE_CREATE_START: 'ActivityTemplate[user_id={userId}] create start frequency={frequency} category={category}',
  TEMPLATE_CREATE_SUCCESS: 'ActivityTemplate[id={id}] create success amount={amount} {unit}',
  TEMPLATE_CREATE_FAILED: 'ActivityTemplate[id={id}] create failed: {field} {reason}',
  TEMPLATE_UPDATE_START: 'ActivityTemplate[id={id}] update start mode={mode} fields={fields}',
  TEMPLATE_UPDATE_SUCCESS: 'ActivityTemplate[id={id}] update success mode={mode}',
  TEMPLATE_ENABLE_START: 'ActivityTemplate[id={id}] enable start backfill through {today}',
  TEMPLATE_PAUSE_SUCCESS: 'ActivityTemplate[id={id}] paused at {pausedAt}',
  TEMPLATE_RESUME_SUCCESS: 'ActivityTemplate[id={id}] resumed anchor={anchorDate}',
  TEMPLATE_DELETE_SUCCESS: 'ActivityTemplate[id={id}] delete success',
  TEMPLATE_BACKFILL_START: 'ActivityTemplate[id={id}] backfill start mode={mode} window=[{low},{high}]',
  TEMPLATE_BACKFILL_SUCCESS: 'ActivityTemplate[id={id}] backfill success inserted={inserted} updated={updated} removed={removed}',
  TEMPLATE_BACKFILL_BUSY: 'ActivityTemplate[id={id}] backfill busy: {reason}',
  TEMPLATE_BACKFILL_SKIPPED: 'ActivityTemplate[id={id}] backfill skipped: {reason}',
  TEMPLATE_GENERATION_INSERT: 'ActivityTemplate[id={id}] generation insert occurrence={occurrenceDate} activity={activityId}',
  TEMPLATE_GENERATION_ADJUSTED: 'ActivityTemplate[id={id}] generation adjusted occurrence={occurrenceDate} preserved',
  TEMPLATE_GENERATION_DETACHED: 'ActivityTemplate[id={id}] generation detached occurrence={occurrenceDate} activity={activityId}',
  TEMPLATE_GENERATION_DELETED: 'ActivityTemplate[id={id}] generation tombstone occurrence={occurrenceDate}',
  FACTOR_LIST_START: `CarbonFactor list start categories=${Object.values(ActivityCategory).join(',')}`,
  FACTOR_CREATE_SUCCESS: 'CarbonFactor[id={id}] create success category={category} region={region}',
  FACTOR_CREATE_FAILED: 'CarbonFactor[id={id}] create failed: {field} {reason}',
  AUDIT_WRITE_START: 'AuditLog[entity={entity}] write start action={action}',
  AUDIT_WRITE_SUCCESS: 'AuditLog[id={id}] write success entity={entity}',
  AUDIT_WRITE_FAILED: 'AuditLog[entity={entity}] write failed: {reason}',
  AUTH_GUARD_GRANTED: 'Auth[user_id={id}] guard granted',
  AUTH_GUARD_DENIED: 'Auth[token={token}] guard denied: {reason}',
  RBAC_GRANTED: 'RBAC[user_id={id}] role granted required={roles}',
  RBAC_DENIED: 'RBAC[user_id={id}] role denied required={roles}',
  HEALTH_CHECK: 'System[health] backend health check'
} as const;

export type LogTemplateKey = keyof typeof LogTemplates;

